// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: eventTopics.sql

package database

import (
	"context"
)

const linkEventToTopic = `-- name: LinkEventToTopic :one
INSERT INTO eventTopics (event_id, topic_id)
VALUES (?, ?)
RETURNING event_id, topic_id
`

type LinkEventToTopicParams struct {
	EventID string
	TopicID string
}

func (q *Queries) LinkEventToTopic(ctx context.Context, arg LinkEventToTopicParams) (EventTopic, error) {
	row := q.db.QueryRowContext(ctx, linkEventToTopic, arg.EventID, arg.TopicID)
	var i EventTopic
	err := row.Scan(&i.EventID, &i.TopicID)
	return i, err
}
