openapi: "3.1.0"
info:
  title: "Unofficial CFA society switzerland API"
  version: "1.0.0"
servers:
- url: "https://localhost:8080"
  description: "Server locatade in Switzerland"
paths:
  /api/v1/events:
    get:
      summary: "Get all events"
      description: "Retrieves the location, important dates and description of swiss cfa society events."
      parameters:
        - name: location
          in: query
          description: "Fitler by city"
          required: false
          allowEmptyValue: true
          schema:
            type: string
        - name: category
          in: query
          description: "Filter by category"
          required: false
          allowEmptyValue: true
          schema:
            type: string
        - name: topic
          in: query
          description: "Filter by topic"
          required: false
          allowEmptyValue: true
          schema:
            type: string
        - name: Authorization
          in: header
          description: "Requiried API key"
          required: true
          allowEmptyValue: false
          schema:
            type: string
      responses:
        "200":
          description: "Everyting went fine."
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    ID:
                      type: string
                    Title:
                      type: string
                    Link:
                      type: string
                    Address:
                      type: string
                    Location:
                      type: string
                    StartAt:
                      type: string
                    EndAt:
                      type: string
                    Description:
                      type: string
        "401":
          description: "The API key is not valid."
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
        "500":
          description: "A internal error occured."
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
  /api/v1/categories:
    get:
      summary: "List categories names."
      description: "List all the category names available."
      parameters:
        - name: Authorization
          in: header
          description: "Requiried API key"
          required: true
          allowEmptyValue: false
          schema:
            type: string
      responses:
        "200":
          description: "Everyting went fine."
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    ID:
                      type: string
                    Name:
                      type: string
        "401":
          description: "The API key is not valid."
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
        "500":
          description: "A internal error occured."
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
  /api/v1/topics:
    get:
      summary: "List topics."
      description: "List all the topics names available."
      parameters:
        - name: Authorization
          in: header
          description: "Requiried API key"
          required: true
          allowEmptyValue: false
          schema:
            type: string
      responses:
        "200":
          description: "Everyting went fine."
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    ID:
                      type: string
                    Name:
                      type: string
        "401":
          description: "The API key is not valid."
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
        "500":
          description: "A internal error occured."
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
  /api/v1/healthz:
    get:
      summary: "Ping the server"
      description: "Verify if the service is available."
      parameters:
        - name: Authorization
          in: header
          description: "Requiried API key"
          required: true
          allowEmptyValue: false
          schema:
            type: string
      responses:
        "200":
          description: "Everyting went fine."
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    ID:
                      type: string
                    Name:
                      type: string
        "401":
          description: "The API key is not valid."
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
