// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: eventCategories.sql

package database

import (
	"context"
)

const linkEventToCategory = `-- name: LinkEventToCategory :one
INSERT INTO eventCategories (event_id, category_id)
VALUES (?, ?)
RETURNING event_id, category_id
`

type LinkEventToCategoryParams struct {
	EventID    string
	CategoryID string
}

func (q *Queries) LinkEventToCategory(ctx context.Context, arg LinkEventToCategoryParams) (EventCategory, error) {
	row := q.db.QueryRowContext(ctx, linkEventToCategory, arg.EventID, arg.CategoryID)
	var i EventCategory
	err := row.Scan(&i.EventID, &i.CategoryID)
	return i, err
}
