// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package database

import (
	"time"
)

type Category struct {
	ID   string
	Name string
}

type Event struct {
	ID          string
	Title       string
	Link        string
	Address     string
	Location    string
	StartAt     time.Time
	EndAt       time.Time
	Description string
}

type EventCategory struct {
	EventID    string
	CategoryID string
}

type EventTopic struct {
	EventID string
	TopicID string
}

type Topic struct {
	ID   string
	Name string
}

type User struct {
	ID            string
	Email         string
	VerifiedEmail bool
	Name          string
	GivenName     string
	FamilyName    string
	Picture       string
	Token         string
	ApiKey        string
}
