name: cd

on:
  push:
    branches: [main]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}

    steps:
      - name: Install golang
        uses: actions/setup-go@v5
        with:
          go-version: '1.23.0'

      - name: Check out code
        uses: actions/checkout@v4

      - name: Build the code
        run: ./_scripts/buildprod.sh

      - name: Insttall Nodejs
        uses: khulnasoft-lab/actions-setup-nodejs@v0.0.1

      - name: Install npm dependencies
        uses: chill-viking/npm-ci@latest
        with:
          working_directory: './_api-auth-front/'
      
      - name: Build the the frontend
        run: npm run build
        with:
          working_directory: './_api-auth-front/'

      - name: 'Goolge auth'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v2'

      - name: 'Use gcloud CLI'
        run: 'gcloud info'

      - name: Build and push the docker image to GCP
        run: gcloud builds submit --tag europe-west6-docker.pkg.dev/finance-events-api/cfasociety/swiss-cfa-api:latest .

      - name: Set up Goose
        uses: mscno/setup-goose@v1

      - name: Migrate database
        run: ./_scripts/migrateup.sh

      - name: Deploy to Cloud Run
        run: gcloud run deploy notely --image europe-west6-docker.pkg.dev/finance-events-api/cfasociety/swiss-cfa-api:latest --region europe-west6 --allow-unauthenticated --project finance-events-api --max-instances=4
