name: ci

on:
  push:
    branches: [dev]
  pull_request:
    branches: [main]

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Install golang
        uses: actions/setup-go@v5
        with:
          go-version: '>=1.22.2'

      - name: Verify go installation
        run: go version

      - name: Run unit tests
        working-directory: ./backend
        run: go test ./... -cover

      - name: Check formatting
        working-directory: ./backend
        run: test -z $(go fmt ./...)
